import type { TablesInsert, Tables } from "./db/database.types";

//
// Auth
//

/**
 * Represents an authenticated user.
 */
export interface AuthUserDTO {
  id: string;
  email: string;
}

/**
 * Command to register a new user.
 */
export interface RegisterUserCommand {
  email: string;
  password: string;
}

/**
 * Response returned after authentication (register/login).
 */
export interface AuthResponseDTO {
  user: AuthUserDTO;
  accessToken: string;
}

// Login uses the same types as register
export type LoginCommand = RegisterUserCommand;
export type LoginResponseDTO = AuthResponseDTO;

//
// Preferences
//

/**
 * DTO for a dietary preference.
 */
export type PreferenceDTO = Tables<"preferences">;

/**
 * Response wrapping a list of preferences.
 */
export interface PreferencesResponseDTO {
  data: PreferenceDTO[];
}

/**
 * DTO for mapping a user to a preference.
 */
export type UserPreferenceDTO = Tables<"user_preferences">;

/**
 * DTO for mapping a recipe to a preference.
 */
export type RecipePreferenceDTO = Tables<"recipe_preferences">;

/**
 * Response wrapping a list of user preferences.
 */
export interface UserPreferencesResponseDTO {
  data: UserPreferenceDTO[];
}

/**
 * Response wrapping a list of recipe preferences.
 */
export interface RecipePreferencesResponseDTO {
  data: RecipePreferenceDTO[];
}

/**
 * Command to update the current user's preferences.
 */
export interface UpdateUserPreferencesCommand {
  preferences: string[];
}

/**
 * Command to update a recipe's preferences.
 */
export interface UpdateRecipePreferencesCommand {
  preferences: string[];
}

/**
 * Response returned after updating user preferences.
 */
export interface UpdateUserPreferencesResponseDTO {
  data: UserPreferenceDTO[];
}

/**
 * Response returned after updating recipe preferences.
 */
export interface UpdateRecipePreferencesResponseDTO {
  data: RecipePreferenceDTO[];
}

//
// Extended Preferences Types
//

/**
 * Extended DTO for user preference that includes preference name.
 */
export type ExtendedUserPreferenceDTO = UserPreferenceDTO & {
  name: string;
};

/**
 * Extended DTO for recipe preference that includes preference name.
 */
export type ExtendedRecipePreferenceDTO = RecipePreferenceDTO & {
  name: string;
};

/**
 * Response wrapping a list of extended user preferences.
 */
export interface ExtendedUserPreferencesResponseDTO {
  data: ExtendedUserPreferenceDTO[];
}

/**
 * Response wrapping a list of extended recipe preferences.
 */
export interface ExtendedRecipePreferencesResponseDTO {
  data: ExtendedRecipePreferenceDTO[];
}

//
// Recipes
//

/**
 * DTO representing a recipe.
 */
export type RecipeDTO = Tables<"recipes">;

/**
 * Extended DTO for a recipe that includes its preferences.
 */
export interface ExtendedRecipeDTO extends RecipeDTO {
  recipe_preferences: {
    preference: {
      id: string;
      name: string;
    };
  }[];
}

/**
 * Metadata for paginated recipe lists.
 */
export interface ListRecipesMeta {
  page: number;
  limit: number;
  total: number;
}

/**
 * Response wrapping a paginated list of recipes.
 */
export interface ListRecipesResponseDTO {
  meta: ListRecipesMeta;
  data: RecipeDTO[];
}

/**
 * Response for retrieving a single recipe.
 */
export type GetRecipeResponseDTO = RecipeDTO;

/**
 * Command to create a new recipe.
 */
export type CreateRecipeCommand = Omit<
  TablesInsert<"recipes">,
  "id" | "user_id" | "created_at" | "updated_at"
> & {
  preference_ids?: string[];
};

/**
 * Response returned after creating a recipe.
 */
export type CreateRecipeResponseDTO = RecipeDTO;

//
// AI Generation
//

/**
 * Command to request recipe generation via AI.
 */
export interface GenerateRecipeCommand {
  prompt: string;
  preferences: string[];
}

/**
 * DTO for a recipe generated by AI.
 */
export interface AIRecipeDTO {
  name: string;
  ingredients: string;
  instructions: string;
  is_ai_generated: boolean;
}

/**
 * Response returned after AI generates a recipe.
 */
export interface GenerateRecipeResponseDTO {
  recipe: AIRecipeDTO;
  disclaimer: string;
}

/**
 * Command to delete a recipe.
 */
export interface DeleteRecipeCommand {
  id: string;
}

/**
 * View model for recipe list item display.
 */
export interface RecipeViewModel {
  id: string;
  name: string;
  ingredients: string;
  instructions: string;
  is_ai_generated: boolean;
  createdAtFormatted: string;
  preferences?: ExtendedRecipePreferenceDTO[];
}
